USE MBGSPMainDB

DROP PROCEDURE [dbo].[SPSRProceduresBuildingMasterfile]
DROP PROCEDURE [dbo].[SPSRProceduresDashboard]
DROP PROCEDURE [dbo].[SPSRProceduresFloorMasterfile]
DROP PROCEDURE [dbo].[SPSRProceduresGS]
DROP PROCEDURE [dbo].[SPSRProceduresLocationMasterfile]
DROP PROCEDURE [dbo].[SPSRProceduresReservationPage]
DROP PROCEDURE [dbo].[SPSRProceduresReservationsPage]
DROP PROCEDURE [dbo].[SPSRProceduresSeatMasterfile]
DROP PROCEDURE [dbo].[SPSRProceduresTK]
DROP PROCEDURE [dbo].[SPSRProceduresUsersPage]
DROP PROCEDURE [dbo].[SPSRProceduresZoneMasterfile]
DROP PROCEDURE [dbo].[SPSRSearchReservationAvailable]
DROP PROCEDURE [dbo].[SPUserPreferenceProcedures]
DROP PROCEDURE [dbo].[SPSRProceduresSetup]